---
fixtures:
  repositories:
    cron_core:
      repo: https://github.com/simp/pupmod-puppetlabs-cron_core
      puppet_version: '>= 6.0.0'
    stdlib: https://github.com/puppetlabs/puppetlabs-stdlib.git
    simplib: https://github.com/simp/pupmod-simp-simplib.git
  symlinks:
    rkhunter: "#{source_dir}"
